language: node_js
node_js:
  - "0.10"
  - "0.8"
  - "0.6"
before_install:
  - git submodule update --init --recursive
  - sudo apt-get install libreadline-dev libconfig-dev libssl-dev libevent-dev make  
  - npm install mocha -g
